# Generated by Django 5.0.4 on 2025-01-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayoff',
            name='nation_cd',
            field=models.CharField(max_length=20, verbose_name='국가코드'),
        ),
    ]
