# Generated by Django 5.0.4 on 2025-01-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_holidayoff_nation_cd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('Code', 'Site')},
        ),
        migrations.AddField(
            model_name='company',
            name='BusinessItem',
            field=models.CharField(max_length=50, null=True, verbose_name='종목'),
        ),
        migrations.AddField(
            model_name='company',
            name='BusinessType',
            field=models.CharField(max_length=50, null=True, verbose_name='업태'),
        ),
        migrations.AddField(
            model_name='company',
            name='CEOName',
            field=models.CharField(max_length=50, null=True, verbose_name='대표이사'),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyType',
            field=models.CharField(max_length=30, null=True, verbose_name='업체유형'),
        ),
        migrations.AddField(
            model_name='company',
            name='Country',
            field=models.CharField(max_length=50, null=True, verbose_name='국가'),
        ),
        migrations.AddField(
            model_name='company',
            name='Description',
            field=models.CharField(max_length=500, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='company',
            name='FaxNumber',
            field=models.CharField(max_length=100, null=True, verbose_name='팩스번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='Homepage',
            field=models.CharField(max_length=100, null=True, verbose_name='홈페이지'),
        ),
        migrations.AddField(
            model_name='company',
            name='Local',
            field=models.CharField(max_length=50, null=True, verbose_name='지역명'),
        ),
        migrations.AddField(
            model_name='company',
            name='Manager',
            field=models.CharField(max_length=50, null=True, verbose_name='담당자1'),
        ),
        migrations.AddField(
            model_name='company',
            name='Manager2',
            field=models.CharField(max_length=50, null=True, verbose_name='담당자2'),
        ),
        migrations.AddField(
            model_name='company',
            name='Manager2Phone',
            field=models.CharField(max_length=50, null=True, verbose_name='담당자2전화번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='ManagerPhone',
            field=models.CharField(max_length=50, null=True, verbose_name='담당자2전화번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='TelNumber',
            field=models.CharField(max_length=100, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='ZipCode',
            field=models.CharField(max_length=50, null=True, verbose_name='우편번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='_creater_nm',
            field=models.CharField(max_length=10, null=True, verbose_name='작성자명'),
        ),
        migrations.AddField(
            model_name='company',
            name='_modifier_nm',
            field=models.CharField(max_length=10, null=True, verbose_name='변경자명'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Address',
            field=models.CharField(db_column='addr', max_length=1000, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Code',
            field=models.CharField(max_length=50, null=True, verbose_name='업체코드'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Email',
            field=models.EmailField(max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Name',
            field=models.CharField(max_length=75, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='domain.site'),
        ),
        migrations.AlterField(
            model_name='company',
            name='_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='_modfied'),
        ),
        migrations.AlterField(
            model_name='holidayoff',
            name='nation_cd',
            field=models.CharField(max_length=10, verbose_name='국가코드'),
        ),
        migrations.AlterField(
            model_name='tagmaster',
            name='tag_name',
            field=models.CharField(max_length=100, verbose_name='태그명'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='BusinessDesc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='CustomerYn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Remark',
        ),
        migrations.RemoveField(
            model_name='company',
            name='SupplierYn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='TelNo',
        ),
    ]
