
sudo mkdir -p /mnt/postgres_data/ts_ai
sudo chown postgres:postgres /mnt/postgres_data/ts_ai


CREATE SCHEMA ai AUTHORIZATION plant_i;
CREATE TABLESPACE ts_ai OWNER plant_i LOCATION 'D:\Program Files\PostgreSQL\16\data\ts_ai';
--CREATE TABLESPACE ts_ai OWNER plant_i LOCATION '/mnt/postgres_data/ts_ai';--리눅스


-- public.ds_model_data definition

-- Drop table

-- DROP TABLE public.ds_model_data;

CREATE TABLE ai.ds_model_data (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"RowIndex" int4 NOT NULL,
	"Code" varchar(50) NOT NULL,
	"Type" varchar(50) NULL,
	"Char1" varchar(200) NULL,
	"Number1" float8 NULL,
	"Date1" timestamptz NULL,
	"Text1" text NULL,
	"_status" varchar(10) NULL,
	"_created" timestamptz NOT NULL,
	"_modified" timestamptz NULL,
	"_creater_id" int4 NULL,
	"_modifier_id" int4 NULL,
	"_creater_nm" varchar(10) NULL,
	"_modifier_nm" varchar(10) NULL,
	"DsModel_id" int4 NULL,
	CONSTRAINT "ds_model_data_DsModel_id_RowIndex_Code_49a4dead_uniq" UNIQUE ("DsModel_id", "RowIndex", "Code"),
	CONSTRAINT ds_model_data_pkey PRIMARY KEY (id)
)
TABLESPACE ts_ai;

CREATE INDEX "ds_model_data_DsModel_id_5917f12d" ON ai.ds_model_data USING btree ("DsModel_id") TABLESPACE ts_ai;


-- ai.ds_model_data foreign keys

ALTER TABLE ai.ds_model_data ADD CONSTRAINT "ds_model_data_DsModel_id_5917f12d_fk_ds_model_id" FOREIGN KEY ("DsModel_id") REFERENCES public.ds_model(id) DEFERRABLE INITIALLY DEFERRED;

